install: check for executable

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,9 +8,17 @@ fi
 REPO=$(dirname "$0")
 
 for location in "boot" "etc" "usr" "var"; do
+	[[ $(command -v rsync) ]] || {
+		echo 'rsync is not founded. is it installed?'
+		exit 1
+	}
 	rsync -ahKv "$REPO/$location/" "/$location"
 done
 
 for terminfo in "$REPO"/terminfo/*; do
+	[[ $(command -v tic) ]] || {
+		echo 'tic is not founded. is it installed?'
+		exit 1
+	}
 	tic -sx "$terminfo"
 done
